/* tslint:disable */
/* eslint-disable */
/**
 * Croct Export
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.1
 * Contact: apis@croct.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiProblem {
    [key: string]: any;

    'title': string;
    'type': string;
    'details'?: string;
}
/**
 * The information about an audience.
 */
export interface Audience {
    /**
     * The ID that uniquely identifies the audience.
     */
    'id'?: string;
    /**
     * The name of the audience.
     */
    'name'?: string | null;
    /**
     * The custom ID of the audience.
     */
    'customId'?: string | null;
}
export interface AudienceMatched extends EventPayload {
    'audienceIds'?: Array<Audience>;
}
/**
 * The available information about a browser.
 */
export interface Browser {
    /**
     * The name of the browser, non-empty. For example, \"Chrome\".
     */
    'name': string | null;
    /**
     * The version of the browser, non-empty. For example, \"79.0.3945.130\", \"11\" or \"160.1\".
     */
    'version': string | null;
    'type': BrowserType;
}


/**
 * The type of the browser.
 */

export const BrowserType = {
    WEB: 'WEB',
    IN_APP: 'IN_APP',
    CRAWLER: 'CRAWLER',
    OTHER: 'OTHER',
    UNKNOWN: 'UNKNOWN',
} as const;

export type BrowserType = typeof BrowserType[keyof typeof BrowserType];


export interface Campaign {
    /**
     * The product promotion or strategic campaign. For example, \"super_promo\".
     */
    'name'?: string | null;
    /**
     * The advertiser that sent traffic to the application. For example, \"newsletter4\".
     */
    'source'?: string | null;
    /**
     * The advertising or marketing medium. For example, \"email\".
     */
    'medium'?: string | null;
    /**
     * The specific content item related the campaign. For example, \"Buy now!\".
     */
    'content'?: string | null;
    /**
     * The search keywords. Foe example, \"web personalization\"
     */
    'term'?: string | null;
}
/**
 * A shopping cart in an online store.
 */
export interface Cart {
    /**
     * The currency in which the monetary values are expressed in the shopping cart. The currency should be specified using the 3-letter currency codes defined by the ISO 4217 standard. For currencies having no official recognition in ISO 4217, as is the case with cryptocurrencies, it is allowed the use of non-ISO codes adopted locally or commercially. For example, \"BRL\" for Brazilian real or \"BTC\" for Bitcoin.
     */
    'currency': string;
    /**
     * The list of items in the shopping cart.
     */
    'items': Array<CartItem>;
    /**
     * The total of all items and quantities in the shopping cart including applied item promotions. Applied order discounts, estimated shipping, and applied shipping discounts should be excluded from the subtotal amount.
     */
    'subtotal': number | null;
    /**
     * The total shipping price for the items in the shopping cart, including any handling charges.
     */
    'shippingPrice': number | null;
    /**
     * The taxes associated with the transaction.
     */
    'taxes': object | null;
    /**
     * The costs associated with the transaction, such as manufacturing costs, shipping expenses not borne by the customer, or any other costs.
     */
    'costs': object | null;
    /**
     * The amount of the discount applied to the shopping cart.
     */
    'discount': number | null;
    /**
     * The total revenue or grand total associated with the transaction. It includes shipping, tax, and any other adjustment.
     */
    'total': number;
    /**
     * The coupon applied to the shopping cart. For example, \"SUPER_DEALS\".
     */
    'coupon': string | null;
    /**
     * The timestamp when the shopping cart was last updated, in milliseconds since epoch.
     */
    'lastUpdateTime': number;
}
export interface CartAbandoned extends EventPayload {
    'cart': Cart;
}
/**
 * An item in a shopping cart.
 */
export interface CartItem {
    /**
     * The index, starting from zero, representing the order in which the item was added to the shopping cart.
     */
    'index': number;
    'product': ProductDetails;
    /**
     * The number of units of the item in the shopping cart.
     */
    'quantity': number;
    /**
     * The total for the item. It includes discounts and any other adjustment.
     */
    'total': number;
    /**
     * The amount of the discount applied to the item.
     */
    'discount': number | null;
    /**
     * The coupon applied to the item. For example, \"SUPER_DEALS\".
     */
    'coupon': string | null;
}
export interface CartModified extends EventPayload {
    'cart': Cart;
}
export interface CartViewed extends EventPayload {
    'cart': Cart;
}
export interface CheckoutStarted extends EventPayload {
    'cart': Cart;
    /**
     * The ID that uniquely identifies the order across the store.
     */
    'orderId': string | null;
}
export interface ClientDetected extends EventPayload {
    'client': WebClient;
}
/**
 * The official currency used in the location.
 */
export interface Currency {
    /**
     * The common name of the currency. For example, \'US Dollar\'.
     */
    'name'?: string | null;
    /**
     * The currency code. For example, USD.
     */
    'code'?: string | null;
}
/**
 * The available information about a device.
 */
export interface Device {
    /**
     * The name of the device, non-empty. For example, \"Mac\", \"iPhone\" or \"Nexus 10\".
     */
    'name': string | null;
    /**
     * The vendor of the device, non-empty. For example, \"Apple\", \"Samsung\" or \"LG\".
     */
    'vendor': string | null;
    'category': DeviceCategory;
    'operatingSystem': OperatingSystem;
}


/**
 * The category of the device.
 */

export const DeviceCategory = {
    DESKTOP: 'DESKTOP',
    TABLET: 'TABLET',
    MOBILE: 'MOBILE',
    BOT: 'BOT',
    OTHER: 'OTHER',
    UNKNOWN: 'UNKNOWN',
} as const;

export type DeviceCategory = typeof DeviceCategory[keyof typeof DeviceCategory];


export interface Event {
    /**
     * The unique identifier of the event.
     */
    'id': string;
    /**
     * The ID of the session assigned to the event.
     */
    'sessionId': string;
    /**
     * The internal ID of the user who originated the event.
     */
    'userId': string;
    /**
     * The timestamp when the event was tracked, in milliseconds since epoch.
     */
    'timestamp': number;
    'context': EventContext | null;
    'payload': EventPayload;
}
/**
 * The context of the client when the event was tracked.
 */
export interface EventContext {
    'type': string;
    'metadata'?: { [key: string]: string | undefined; };
}
export interface EventOccurred extends EventPayload {
    /**
     * The name of the event. For example, \"pollAnswered\" or \"onboardingStarted\".
     */
    'name': string;
    /**
     * The details about the event.
     */
    'details': object;
}
/**
 * The event details, specific to the type of event.
 */
export interface EventPayload {
    '@type': string;
}
export interface EventResponse {
    'items': Array<Event>;
    'metadata': EventResponseMetadata;
    'nextCursor': string;
}
export interface EventResponseMetadata {
    'organizationName': string;
    'organizationSlug': string;
    'workspaceName': string;
    'workspaceSlug': string;
    'applicationName': string;
    'applicationSlug': string;
}

export const EventType = {
    USER_SIGNED_UP: 'userSignedUp',
    USER_SIGNED_IN: 'userSignedIn',
    USER_SIGNED_OUT: 'userSignedOut',
    TAB_OPENED: 'tabOpened',
    TAB_URL_CHANGED: 'tabUrlChanged',
    TAB_VISIBILITY_CHANGED: 'tabVisibilityChanged',
    LOCATION_DETECTED: 'locationDetected',
    CLIENT_DETECTED: 'clientDetected',
    PAGE_OPENED: 'pageOpened',
    PAGE_LOADED: 'pageLoaded',
    PRODUCT_ABANDONED: 'productAbandoned',
    PRODUCT_VIEWED: 'productViewed',
    CART_ABANDONED: 'cartAbandoned',
    CART_VIEWED: 'cartViewed',
    CART_MODIFIED: 'cartModified',
    CHECKOUT_STARTED: 'checkoutStarted',
    ORDER_PLACED: 'orderPlaced',
    NOTHING_CHANGED: 'nothingChanged',
    GOAL_COMPLETED: 'goalCompleted',
    EVENT_OCCURRED: 'eventOccurred',
    SLOT_PERSONALIZED: 'slotPersonalized',
    LEAD_GENERATED: 'leadGenerated',
    AUDIENCE_MATCHED: 'audienceMatched',
    USER_CLICKED: 'userClicked',
    USER_SCROLLED: 'userScrolled',
} as const;

export type EventType = typeof EventType[keyof typeof EventType];


/**
 * A geographic location represented by a latitude and longitude coordinates pair.
 */
export interface GeoPoint {
    /**
     * The latitude of the geo-point, may be either negative or positive.
     */
    'latitude': number;
    /**
     * The longitude of the geo-point, may be either negative or positive.
     */
    'longitude': number;
}
export interface GoalCompleted extends EventPayload {
    /**
     * The ID of the goal.
     */
    'goalId': string;
    /**
     * The monetary value associated to the completion of the goal. This can represent an estimated value or a symbolic value. For example, if the sales team can close 10% of people who sign up for a newsletter, and the average transaction is $500, then a possible value for newsletter sign-ups can be $50 (i.e., 10% of $500).
     */
    'value': string | null;
    /**
     * The currency in which the monetary value is expressed. The currency should be specified using the 3-letter currency codes defined by the ISO 4217 standard. For currencies having no official recognition in ISO 4217, as is the case with cryptocurrencies, it is allowed the use of non-ISO codes adopted locally or commercially. For example, \"BRL\" for Brazilian real or \"BTC\" for Bitcoin.
     */
    'currency': string | null;
}
export interface LeadGenerated extends EventPayload {
    /**
     * An identifier supplied by the application to uniquely identify the lead.
     */
    'leadId'?: string;
    /**
     * The currency in which the lead value is accounted.
     */
    'currency'?: string;
    /**
     * The total value associated with the lead.
     */
    'value'?: string;
}
/**
 * An identification or estimation of a geographic location of an object.
 */
export interface Location {
    'continent': LocationContinent | null;
    /**
     * The highest administrative division, also known as a nation. The value is a two-letter country code, as defined in ISO 3166. For example, US for United States, BR for Brazil and DE for Germany.
     */
    'country': string | null;
    'region': Region;
    /**
     * The name of the incorporated city or town political entity. For example, \"Sao Paulo\".
     */
    'city': string | null;
    /**
     * An administrative division smaller than a city and larger than a neighborhood. For example, the district of Manhattan in New York.
     */
    'district': string | null;
    /**
     * The time-zone ID as defined in IANA Time Zone Database. For example, \"America/New_York\".
     */
    'timezone': string | null;
    'coordinates': GeoPoint | null;
    'currency'?: Currency | null;
    /**
     * The international dialing code for this location. For example, \'+1\' or \'+55\'.
     */
    'phoneCode'?: string | null;
    /**
     * The approximate number of people living within the borders of the represented location.
     */
    'population'?: string | null;
    /**
     * The general postal code for the location, such as a starting range, but it may also represent another relevant code for the area. For example, \'12345-678\'.
     */
    'postalCode'?: string | null;
    /**
     * A list of locales following the ISO 639-1 and ISO 3166-1 standards, representing the languages spoken in the location, ordered from the most spoken to the least spoken. For example, \'pt-br\' or \'en-us\'.
     */
    'languages'?: Array<string>;
    /**
     * A list of tags addressing different aspects of a location. For example, \'beach\' or \'ocean\'.
     */
    'tags'?: Array<string>;
    'source': LocationSource | null;
}


/**
 * The continent of the location.
 */

export const LocationContinent = {
    AF: 'AF',
    AN: 'AN',
    AS: 'AS',
    EU: 'EU',
    NA: 'NA',
    OC: 'OC',
    SA: 'SA',
} as const;

export type LocationContinent = typeof LocationContinent[keyof typeof LocationContinent];


export interface LocationDetected extends EventPayload {
    'location': Location;
}
/**
 * The source of information used to determine the location.
 */

export const LocationSource = {
    UNKNOWN: 'UNKNOWN',
    IP: 'IP',
    INPUT: 'INPUT',
    BROWSER: 'BROWSER',
    GPS: 'GPS',
} as const;

export type LocationSource = typeof LocationSource[keyof typeof LocationSource];


export interface NothingChanged extends EventPayload {
    /**
     * The timestamp when an activity was last observed, in milliseconds since epoch.
     */
    'sinceTime': number;
}
/**
 * The available information about an operating system.
 */
export interface OperatingSystem {
    /**
     * The name of the operating system, non-empty. For example, \"macOS\", \"iOS\" or \"Android\".
     */
    'name': string | null;
    /**
     * The version of operating system, non-empty. For example, \"10.15.1\", \"NT 5.1\" or \"8.4\".
     */
    'version': string | null;
}
/**
 * An order placed in an online store.
 */
export interface Order {
    /**
     * The ID that uniquely identifies the order across the store.
     */
    'orderId': string;
    /**
     * The currency in which the monetary values are expressed in the order. The currency should be specified using the 3-letter currency codes defined by the ISO 4217 standard. For currencies having no official recognition in ISO 4217, as is the case with cryptocurrencies, it is allowed the use of non-ISO codes adopted locally or commercially. For example, \"BRL\" for Brazilian real or \"BTC\" for Bitcoin.
     */
    'currency': string;
    /**
     * The list of items in the order.
     */
    'items': Array<OrderItem>;
    /**
     * The total of all items and quantities in the order including applied item promotions. Applied order discounts, estimated shipping, and applied shipping discounts should be excluded from the subtotal amount.
     */
    'subtotal': number | null;
    /**
     * The total shipping price for the order, including any handling charges.
     */
    'shippingPrice': number | null;
    /**
     * The taxes associated with the transaction.
     */
    'taxes': object | null;
    /**
     * The costs associated with the transaction, such as manufacturing costs, shipping expenses not borne by the customer, or any other costs.
     */
    'costs': object | null;
    /**
     * The amount of the discount applied to the order.
     */
    'discount': number | null;
    /**
     * The total revenue or grand total associated with the transaction. It includes shipping, tax, and any other adjustment.
     */
    'total': number;
    /**
     * The coupon applied to the order. For example, \"SUPER_DEALS\".
     */
    'coupon': string | null;
    /**
     * The payment method used in the payment. For example, \"Credit Card\", \"Paypal\" or \"Wallet\".
     */
    'paymentMethod': string | null;
    /**
     * The number of installments of the transaction, non-negative.
     */
    'installments': number | null;
    'status': OrderStatus | null;
}


/**
 * An item of an order.
 */
export interface OrderItem {
    /**
     * The index, starting from zero, representing the order in which the item was added to the shopping cart.
     */
    'index': number;
    'product': ProductDetails;
    /**
     * The number of units of the item ordered.
     */
    'quantity': number;
    /**
     * The total for the item. It includes discounts and any other adjustment.
     */
    'total': number;
    /**
     * The amount of the discount applied to the item.
     */
    'discount': number | null;
    /**
     * The coupon applied to the item. For example, \"SUPER_DEALS\".
     */
    'coupon': string | null;
}
export interface OrderPlaced extends EventPayload {
    'order': Order;
}
/**
 * The current status of the order.
 */

export const OrderStatus = {
    PLACED: 'PLACED',
    PAID: 'PAID',
    COMPLETED: 'COMPLETED',
} as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export interface PageLoaded extends EventPayload {
    /**
     * The URL of the page.
     */
    'url': string;
    /**
     * The title of the page.
     */
    'title': string;
    /**
     * The last time the page was modified.
     */
    'lastModifiedTime': number;
}
export interface PageOpened extends EventPayload {
    /**
     * The URL of the page.
     */
    'url': string;
    /**
     * The user-agent of the client.
     */
    'userAgent': string | null;
    /**
     * An ordered list of the user\'s preferred languages.
     */
    'preferredLanguages': string | null;
    /**
     * The URI of the page that linked to the page that was opened. The value is null when the user navigated to the page directly (not through a link, but by using a bookmark, for example).
     */
    'referrer': string | null;
}
/**
 * A position in a two-dimensional space.
 */
export interface Point {
    /**
     * The horizontal position in pixels.
     */
    'x': number;
    /**
     * The vertical position in pixels.
     */
    'y': number;
}
export interface ProductAbandoned extends EventPayload {
    'cartItem': CartItem;
    'cart': Cart;
}
/**
 * The detailed information of a product.
 */
export interface ProductDetails {
    /**
     * The ID that uniquely identifies the product across the store, non-empty. For example, \"3108\" or \"yO7q4r\".
     */
    'productId': string;
    /**
     * The code that uniquely identifies the product variant across the store, non-empty. For example, \"IPH-GRE-64\".
     */
    'sku': string | null;
    /**
     * The name of the product, non-empty. For example \"iPhone\".
     */
    'name': string;
    /**
     * The category of the product, non-empty. For example, \"Phone\".
     */
    'category': string | null;
    /**
     * The brand associated with the product. For example, \"Apple\".
     */
    'brand': string | null;
    /**
     * The variant of the product, such as size, color and style. For example, \"64GB Green\".
     */
    'variant': string | null;
    /**
     * The price of the product displayed in the store. For example, 59.90.
     */
    'displayPrice': number;
    /**
     * The original price of the product. For example, 99.90.
     */
    'originalPrice': number | null;
    /**
     * The currency in which the monetary values are expressed in the shopping cart.
     */
    'currency'?: string | null;
    /**
     * The URL of the product page. For example, \"https://apple.com/iphone\".
     */
    'url': string | null;
    /**
     * The URL of the main product image. For example, \"https://img.apple.com/iphone.png\".
     */
    'imageUrl': string | null;
}
export interface ProductViewed extends EventPayload {
    'product': ProductDetails;
}
/**
 * A subsection of a country, typically a state or province.
 */
export interface Region {
    /**
     * The subdivision name, non-empty. For example, \"Sao Paulo\".
     */
    'name': string | null;
    /**
     * The 2-letter code as defined by the ISO 3166-2 standard. For example, \"SP\".
     */
    'code': string | null;
}
export interface Session {
    /**
     * The ID that uniquely identifies the session across the application.
     */
    'sessionId'?: string;
    /**
     * The ID that uniquely identifies the user across the workspace.
     */
    'userId'?: string;
    /**
     * The ID of the session that superseded this session. Usually, a session receives a parent ID when a user is identified, causing the current anonymous session to end and a new identified session to begin. In this case, the ID of the new session is assigned as the parent ID of the anonymous session.
     */
    'parentId'?: string | null;
    /**
     * The external user ID that is used to identify the user on the application side, unique across the workspace. It is always null for anonymous users.
     */
    'externalUserId'?: string | null;
    'window'?: SessionWindow;
    /**
     * The time from which the session is closed for new events, but still may accept late-arriving events. The close time may be extended if new events arrive before the session is closed.
     */
    'closeTime'?: number;
    /**
     * The URI of the content that linked to the page that started the session.
     */
    'referrer'?: string | null;
    /**
     * The page that started the session.
     */
    'landingPageUrl'?: string | null;
    'campaign'?: Campaign;
    'location'?: Location;
    'client'?: WebClient;
    /**
     * The custom attributes.
     */
    'attributes'?: { [key: string]: any | undefined | null; };
    'statistics'?: SessionStatistics;
}
export interface SessionResponse {
    'items': Array<Session>;
    'nextCursor': string;
}
/**
 * The aggregated statistics of the session.
 */
export interface SessionStatistics {
    /**
     * The total number of page views.
     */
    'pageViews'?: number;
    /**
     * The total number of tab views.
     */
    'tabViews'?: number;
    /**
     * The total number of orders placed.
     */
    'orders'?: number;
}
/**
 * The time window covering the first and last event of the session.
 */
export interface SessionWindow {
    'start'?: number;
    'end'?: number;
}
export interface SingleEventResponse {
    'metadata': EventResponseMetadata;
    'event': Event;
}
/**
 * A two-dimensional size.
 */
export interface Size {
    /**
     * The width in pixels.
     */
    'width': number;
    /**
     * The height in pixels.
     */
    'height': number;
}
/**
 * An event recording a slot personalization.
 */
export interface SlotPersonalized {
    /**
     * The event type identifier.
     */
    '@type': string;
    'personalization': SlotPersonalizedPersonalization;
    'metadata': SlotPersonalizedMetadata;
}
/**
 * Additional information about the personalization.
 */
export interface SlotPersonalizedMetadata {
    /**
     * The name of the audience.
     */
    'audienceName': string | null;
    /**
     * The custom ID of the audience.
     */
    'audienceCustomId': string | null;
    /**
     * The name of the slot.
     */
    'slotName': string | null;
    /**
     * The custom ID of the slot.
     */
    'slotCustomId': string | null;
    /**
     * The name of the experience.
     */
    'experienceName': string | null;
    /**
     * The name of the experiment.
     */
    'experimentName': string | null;
    /**
     * The name of the variant.
     */
    'variantName': string | null;
}
export interface SlotPersonalizedPersonalization {
    /**
     * The ID that uniquely identifies the audience.
     */
    'audienceId': string;
    /**
     * The ID that uniquely identifies the slot.
     */
    'slotId': string;
    /**
     * The ID that uniquely identifies the experience.
     */
    'experienceId': string;
    /**
     * The ID that uniquely identifies the content.
     */
    'contentId': string;
    'slotVersion'?: SlotPersonalizedPersonalizationSlotVersion | null;
    'assignedVariant': SlotPersonalizedPersonalizationAssignedVariant | null;
    /**
     * The locale of the content.
     */
    'locale'?: string | null;
}
export interface SlotPersonalizedPersonalizationAssignedVariant {
    /**
     * The ID that uniquely identifies the experiment.
     */
    'experimentId'?: string;
    /**
     * The ID that uniquely identifies the variant.
     */
    'variantId'?: string;
}
export interface SlotPersonalizedPersonalizationSlotVersion {
    /**
     * The major version.
     */
    'majorVersion'?: string;
    /**
     * The minor version.
     */
    'minorVersion'?: string;
}
export interface TabOpened extends EventPayload {
    /**
     * The ID that uniquely identifies the tab across the session.
     */
    'tabId': string;
}
export interface TabUrlChanged extends EventPayload {
    /**
     * The ID that uniquely identifies the tab across the session.
     */
    'tabId': string;
    /**
     * The URL the page that the tab was on.
     */
    'url': string;
}
/**
 * The visibility of the tab.
 */

export const TabVisibility = {
    VISIBLE: 'VISIBLE',
    HIDDLE: 'HIDDEN',
} as const;

export type TabVisibility = typeof TabVisibility[keyof typeof TabVisibility];


export interface TabVisibilityChanged extends EventPayload {
    /**
     * The ID that uniquely identifies the tab across the session.
     */
    'tabId': string;
    'visibility': TabVisibility;
}


export interface User {
    /**
     * The internal ID assigned to the user, unique across the workspace.
     */
    'userId'?: string;
    /**
     * The external user ID that is used to identify the user on the application side, unique across the workspace. It is always null for anonymous users.
     */
    'externalUserId'?: string | null;
    /**
     * The first name attribute.
     */
    'firstName'?: string | null;
    /**
     * The last name attribute.
     */
    'lastName'?: string | null;
    /**
     * The birth date attribute.
     */
    'birthDate'?: number | null;
    /**
     * The gender attribute.
     */
    'gender'?: string;
    /**
     * The email attribute.
     */
    'email'?: string | null;
    /**
     * The alternate email attribute.
     */
    'alternateEmail'?: string | null;
    /**
     * The phone attribute.
     */
    'phone'?: string | null;
    /**
     * The alternate phone attribute.
     */
    'alternatePhone'?: string | null;
    'address'?: UserAddress;
    /**
     * The avatar attribute.
     */
    'avatar'?: string | null;
    /**
     * The company attribute.
     */
    'company'?: string | null;
    /**
     * The company URL attribute.
     */
    'companyUrl'?: string | null;
    /**
     * The job title attribute.
     */
    'jobTitle'?: string | null;
    /**
     * The activities attribute.
     */
    'activities'?: Array<string>;
    /**
     * The interests attribute.
     */
    'interests'?: Array<string>;
    /**
     * The custom attributes.
     */
    'customAttributes'?: { [key: string]: any | undefined; };
    /**
     * The timestamp when the user was last modified, in milliseconds since epoch. It is not updated on sync.
     */
    'lastModifiedTime'?: number;
    'statistics'?: UserStatistics;
}
/**
 * The address attribute.
 */
export interface UserAddress {
    'street'?: string | null;
    'district'?: string | null;
    'city'?: string | null;
    'region'?: string | null;
    'country'?: string | null;
    'postalCode'?: string | null;
}
export interface UserClicked extends EventPayload {
    'point': Point;
    'surfaceSize'?: Size;
}
export interface UserResponse {
    'items': Array<User>;
    'nextCursor': string;
}
export interface UserScrolled extends EventPayload {
    'start'?: Point;
    'end': Point;
    'surfaceSize'?: Size;
    'viewportSize'?: Size;
}
export interface UserSignedIn extends EventPayload {
    /**
     * The external ID of the user.
     */
    'externalUserId': string;
}
export interface UserSignedOut extends EventPayload {
    /**
     * The external ID of the user.
     */
    'externalUserId': string;
}
export interface UserSignedUp extends EventPayload {
    /**
     * The external ID of the user.
     */
    'externalUserId': string;
}
/**
 * The aggregated statistics of the user.
 */
export interface UserStatistics {
    /**
     * The total number of orders placed across all applications in a workspace.
     */
    'orders'?: number;
    /**
     * The total number of sessions across all applications in a workspace.
     */
    'sessions'?: number;
}
/**
 * The available information about a web client.
 */
export interface WebClient {
    'browser': Browser;
    'device': Device;
}
export interface WebContext extends EventContext {
    /**
     * The ID that uniquely identifies the tab across the session.
     */
    'tabId': string;
    /**
     * The URL of the page that the client was on.
     */
    'url': string;
}

/**
 * ExportApi - axios parameter creator
 */
export const ExportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id The unique identifier of the event
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportEventById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('exportEventById', 'id', id)
            const localVarPath = `/events/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [start] 
         * @param {number} [end] 
         * @param {number} [pageSize] 
         * @param {string} [cursor] 
         * @param {Array<EventType>} [events] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportEvents: async (start?: number, end?: number, pageSize?: number, cursor?: string, events?: Array<EventType>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (events) {
                localVarQueryParameter['events'] = events;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} sessionId The unique identifier of the session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSessionById: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('exportSessionById', 'sessionId', sessionId)
            const localVarPath = `/session/{sessionId}`
                .replace('{sessionId}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [start] 
         * @param {number} [end] 
         * @param {number} [pageSize] 
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSessions: async (start?: number, end?: number, pageSize?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/session`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId The unique identifier of the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportUserById: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('exportUserById', 'userId', userId)
            const localVarPath = `/user/{userId}`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [start] 
         * @param {number} [end] 
         * @param {number} [pageSize] 
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportUsers: async (start?: number, end?: number, pageSize?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-Api-Key", configuration)

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExportApi - functional programming interface
 */
export const ExportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExportApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id The unique identifier of the event
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportEventById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleEventResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportEventById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.exportEventById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [start] 
         * @param {number} [end] 
         * @param {number} [pageSize] 
         * @param {string} [cursor] 
         * @param {Array<EventType>} [events] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportEvents(start?: number, end?: number, pageSize?: number, cursor?: string, events?: Array<EventType>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportEvents(start, end, pageSize, cursor, events, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.exportEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} sessionId The unique identifier of the session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportSessionById(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Session>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportSessionById(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.exportSessionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [start] 
         * @param {number} [end] 
         * @param {number} [pageSize] 
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportSessions(start?: number, end?: number, pageSize?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportSessions(start, end, pageSize, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.exportSessions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId The unique identifier of the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportUserById(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportUserById(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.exportUserById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [start] 
         * @param {number} [end] 
         * @param {number} [pageSize] 
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportUsers(start?: number, end?: number, pageSize?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportUsers(start, end, pageSize, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.exportUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExportApi - factory interface
 */
export const ExportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExportApiFp(configuration)
    return {
        /**
         * 
         * @param {ExportApiExportEventByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportEventById(requestParameters: ExportApiExportEventByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<SingleEventResponse> {
            return localVarFp.exportEventById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExportApiExportEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportEvents(requestParameters: ExportApiExportEventsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<EventResponse> {
            return localVarFp.exportEvents(requestParameters.start, requestParameters.end, requestParameters.pageSize, requestParameters.cursor, requestParameters.events, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExportApiExportSessionByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSessionById(requestParameters: ExportApiExportSessionByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<Session> {
            return localVarFp.exportSessionById(requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExportApiExportSessionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSessions(requestParameters: ExportApiExportSessionsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<SessionResponse> {
            return localVarFp.exportSessions(requestParameters.start, requestParameters.end, requestParameters.pageSize, requestParameters.cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExportApiExportUserByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportUserById(requestParameters: ExportApiExportUserByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.exportUserById(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExportApiExportUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportUsers(requestParameters: ExportApiExportUsersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.exportUsers(requestParameters.start, requestParameters.end, requestParameters.pageSize, requestParameters.cursor, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for exportEventById operation in ExportApi.
 */
export interface ExportApiExportEventByIdRequest {
    /**
     * The unique identifier of the event
     */
    readonly id: string
}

/**
 * Request parameters for exportEvents operation in ExportApi.
 */
export interface ExportApiExportEventsRequest {
    readonly start?: number

    readonly end?: number

    readonly pageSize?: number

    readonly cursor?: string

    readonly events?: Array<EventType>
}

/**
 * Request parameters for exportSessionById operation in ExportApi.
 */
export interface ExportApiExportSessionByIdRequest {
    /**
     * The unique identifier of the session
     */
    readonly sessionId: string
}

/**
 * Request parameters for exportSessions operation in ExportApi.
 */
export interface ExportApiExportSessionsRequest {
    readonly start?: number

    readonly end?: number

    readonly pageSize?: number

    readonly cursor?: string
}

/**
 * Request parameters for exportUserById operation in ExportApi.
 */
export interface ExportApiExportUserByIdRequest {
    /**
     * The unique identifier of the user
     */
    readonly userId: string
}

/**
 * Request parameters for exportUsers operation in ExportApi.
 */
export interface ExportApiExportUsersRequest {
    readonly start?: number

    readonly end?: number

    readonly pageSize?: number

    readonly cursor?: string
}

/**
 * ExportApi - object-oriented interface
 */
export class ExportApi extends BaseAPI {
    /**
     * 
     * @param {ExportApiExportEventByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportEventById(requestParameters: ExportApiExportEventByIdRequest, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).exportEventById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExportApiExportEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportEvents(requestParameters: ExportApiExportEventsRequest = {}, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).exportEvents(requestParameters.start, requestParameters.end, requestParameters.pageSize, requestParameters.cursor, requestParameters.events, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExportApiExportSessionByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportSessionById(requestParameters: ExportApiExportSessionByIdRequest, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).exportSessionById(requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExportApiExportSessionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportSessions(requestParameters: ExportApiExportSessionsRequest = {}, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).exportSessions(requestParameters.start, requestParameters.end, requestParameters.pageSize, requestParameters.cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExportApiExportUserByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportUserById(requestParameters: ExportApiExportUserByIdRequest, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).exportUserById(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExportApiExportUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportUsers(requestParameters: ExportApiExportUsersRequest = {}, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).exportUsers(requestParameters.start, requestParameters.end, requestParameters.pageSize, requestParameters.cursor, options).then((request) => request(this.axios, this.basePath));
    }
}



